#!/bin/bash
xrandr --output $HDMI --off > /dev/null 2>&1
xrandr --output HDMI-1 --auto > /dev/null 2>&1
ubicacion="/usr/share/lxqt/themes/dark"
echo "Este script hace uso de pcmanfm-qt, si presenta error instale pcmanfm-qt"
dpkg -s pcmanfm-qt > /dev/null 2>&1
if [ $? -ne 0 ]
   then
      echo "Instalando pcmanfm-qt..."
      sudo apt-get update -y > /dev/null 2>&1
      sudo apt-get install pcmanfm-qt -y > /dev/null 2>&1
else
pcm=$(dpkg -s pcmanfm-qt | grep "Status:" | awk '{print substr($0,9, length($0) -0)}')
echo -e "Pcmanfm-qt: \033[1;36m${pcm}\033[0m"
fi

HDMI=$(xrandr --current | grep -w "HDMI" | head -c 6)
VGA=$(xrandr --current | grep -w "VGA" | head -c 5)

rHDMI=$(xrandr | grep '*' | tail -n 1 | sort -r | awk '{print substr($0,4, length($0) -0)}' | head -c 9)

rVGA=$(xrandr | grep '*' | sort -r | tail -n 1 | awk '{print substr($0,4, length($0) -0)}'| head -c 9)

if [ $rHDMI == $rVGA ]
   then
      echo "No se ha detectado ningun monitor extermo. Conecte y vuelva a ejecutar"
       
fi

xrandr | grep "HDMI" > /dev/null 2>&1
if [ $? -ne 0 ]
   then
      echo "No hay dispositivos HDMI conectados..."
else
echo -e "\033[1;32m${HDMI}\033[0m"
fi

echo "Usar pantalla HDMI?"
read c
if [ "$c" == "y" ] || [ "$c" == "yes" ] || [ "$c" == "YES" ] || [ "$c" == "Y" ] || [ "$c" == "si" ] || [ "$c" == "sí" ] || [ "$c" == "SI" ] || [ "$c" == "SÍ" ] || [ "$c" == "s" ] || [ "$c" == "S" ]
   then
	echo "Usar HDMI como pantalla principal?"
	read s
	
	if [ "$s" == "y" ] || [ "$s" == "yes" ] || [ "$s" == "YES" ] || [ "$s" == "Y" ] || [ "$s" == "si" ] || [ "$s" == "sí" ] || [ "$s" == "SI" ] || [ "$s" == "SÍ" ] || [ "$s" == "s" ] || [ "$s" == "S" ]
   	   then
   	   
   	   echo "arriba?"
   	   read up
   	   	if [ "$up" == "y" ] || [ "$up" == "yes" ] || [ "$up" == "YES" ] || [ "$up" == "Y" ] || [ "$up" == "si" ] || [ "$up" == "sí" ] || [ "$up" == "SI" ] || [ "$up" == "SÍ" ] || [ "$up" == "s" ] || [ "$up" == "S" ]
   	   	then
   	   	pcmanfm-qt -w "$(find $ubicacion/above.png -type f | shuf -n1)"
   	   	xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $rVGA --above $HDMI > /dev/null 2>&1
   	   		if [ $? -ne 0 ]
   	   		then
   	   		echo "No hay dispositivos HDMI conectados..."
			pcmanfm-qt -w "$(find $ubicacion/above.png -type f | shuf -n1)"
			xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $rVGA --above $HDMI > /dev/null 2>&1
			else
			echo "El monitor tiene una resolucion correcta? si/no"
			read mn
				if [ "$mn" == "n" ] || [ "$mn" == "no" ] || [ "$mn" == "No" ] || [ "$mn" == "NO" ] || [ "$lk" == "not" ] || [ "$lk" == "NOT" ] || [ "$Not" == "N" ]
				then
					xrandr | grep '*' | tail -n 1 | sort -r | awk '{print substr($0,4, length($0) -13)}'
					echo "Ingrese la resolucion"
					read res
					pcmanfm-qt -w "$(find $ubicacion/above.png -type f | shuf -n1)"
					xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $res --above $HDMI > /dev/null 2>&1
					echo "Echo resoluccion seleccionada"
					 
				else
				echo "Aplicado..."
				 
				fi				
            fi
        else
        echo "abajo?"
        read down
        if [ "$down" == "y" ] || [ "$down" == "yes" ] || [ "$down" == "YES" ] || [ "$down" == "Y" ] || [ "$down" == "si" ] || [ "$down" == "sí" ] || [ "$down" == "SI" ] || [ "$down" == "SÍ" ] || [ "$down" == "s" ] || [ "$down" == "S" ]
   	   	then
   	   	pcmanfm-qt -w "$(find $ubicacion/down.png -type f | shuf -n1)"
		xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $rVGA --below $HDMI > /dev/null 2>&1
   	   		if [ $? -ne 0 ]
   	   		then
   	   		echo "No hay dispositivos HDMI conectados..."
			pcmanfm-qt -w "$(find $ubicacion/down.png -type f | shuf -n1)"
			xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $rVGA --below $HDMI > /dev/null 2>&1
			else
			echo "El monitor tiene una resolucion correcta? si/no"
			read mn
				if [ "$mn" == "n" ] || [ "$mn" == "no" ] || [ "$mn" == "No" ] || [ "$mn" == "NO" ] || [ "$lk" == "not" ] || [ "$lk" == "NOT" ] || [ "$Not" == "N" ]
				then
					xrandr | grep '*' | tail -n 1 | sort -r | awk '{print substr($0,4, length($0) -13)}'
					echo "Ingrese la resolucion"
					read res
					pcmanfm-qt -w "$(find $ubicacion/down.png -type f | shuf -n1)"
					xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $res --below $HDMI > /dev/null 2>&1
					echo "Echo resoluccion seleccionada"
					 
				else
				echo "Aplicado..."
				 
				fi				
            fi
        else
        echo "Izquierda?"
   	   	read left
   	   	if [ "$left" == "y" ] || [ "$left" == "yes" ] || [ "$left" == "YES" ] || [ "$left" == "Y" ] || [ "$left" == "si" ] || [ "$left" == "sí" ] || [ "$left" == "SI" ] || [ "$left" == "SÍ" ] || [ "$left" == "s" ] || [ "$left" == "S" ]
   	   	then
   	   	pcmanfm-qt -w "$(find $ubicacion/left.png -type f | shuf -n1)"
   	   	xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $rVGA --left-of $HDMI > /dev/null 2>&1
   	   		if [ $? -ne 0 ]
   	   		then
   	   		echo "No hay dispositivos HDMI conectados..."
			pcmanfm-qt -w "$(find $ubicacion/left.png -type f | shuf -n1)"
   	   		xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $rVGA --left-of $HDMI > /dev/null 2>&1
			else
			echo "El monitor tiene una resolucion correcta? si/no"
			read mn
				if [ "$mn" == "n" ] || [ "$mn" == "no" ] || [ "$mn" == "No" ] || [ "$mn" == "NO" ] || [ "$lk" == "not" ] || [ "$lk" == "NOT" ] || [ "$Not" == "N" ]
				then
					xrandr | grep '*' | tail -n 1 | sort -r | awk '{print substr($0,4, length($0) -13)}'
					echo "Ingrese la resolucion"
					read res
					pcmanfm-qt -w "$(find $ubicacion/above.png -type f | shuf -n1)"
					xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $res --left-of $HDMI > /dev/null 2>&1
					echo "Echo resoluccion seleccionada"
					 
				else
				echo "Aplicado..."
				 
				fi				
            fi
        else
   	   	pcmanfm-qt -w "$(find $ubicacion/right.png -type f | shuf -n1)"
   	   	xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $rVGA --right-of $HDMI > /dev/null 2>&1
   	   		if [ $? -ne 0 ]
   	   		then
   	   		echo "No hay dispositivos HDMI conectados..."
			pcmanfm-qt -w "$(find $ubicacion/right.png -type f | shuf -n1)"
			xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $rVGA --right-of $HDMI > /dev/null 2>&1
			else
			echo "El monitor tiene una resolucion correcta? si/no"
			read mn
				if [ "$mn" == "n" ] || [ "$mn" == "no" ] || [ "$mn" == "No" ] || [ "$mn" == "NO" ] || [ "$lk" == "not" ] || [ "$lk" == "NOT" ] || [ "$Not" == "N" ]
				then
					xrandr | grep '*' | tail -n 1 | sort -r | awk '{print substr($0,4, length($0) -13)}'
					echo "Ingrese la resolucion"
					read res
					pcmanfm-qt -w "$(find $ubicacion/right.png -type f | shuf -n1)"
					xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $res --right-of $HDMI > /dev/null 2>&1
					echo "Echo resoluccion seleccionada"
					 
				else
				echo "Aplicado..."
				 
				fi				
       	fi
       	fi
       	fi
       	fi
    else
    echo "Usar HDMI como pantalla extendida?"
	read lk
		if [ "$lk" == "y" ] || [ "$lk" == "yes" ] || [ "$lk" == "YES" ] || [ "$lk" == "Y" ] || [ "$lk" == "si" ] || [ "$lk" == "sí" ] || [ "$lk" == "SI" ] || [ "$lk" == "SÍ" ] || [ "$lk" == "s" ] || [ "$lk" == "S" ] || [ "$lk" == "Si" ]  || [ "$lk" == "Sí" ]
   		then
		  	xrandr --output $VGA --auto --primary
			echo "arriba?"
   	   		read up
   	   		if [ "$up" == "y" ] || [ "$up" == "yes" ] || [ "$up" == "YES" ] || [ "$up" == "Y" ] || [ "$up" == "si" ] || [ "$up" == "sí" ] || [ "$up" == "SI" ] || [ "$up" == "SÍ" ] || [ "$up" == "s" ] || [ "$up" == "S" ]
   	   		then
   	   		pcmanfm-qt -w "$(find $ubicacion/above.png -type f | shuf -n1)"
   	   		xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $rVGA --above $HDMI > /dev/null 2>&1
   	   		if [ $? -ne 0 ]
   	   		then
   	   		echo "No hay dispositivos HDMI conectados..."
			pcmanfm-qt -w "$(find $ubicacion/above.png -type f | shuf -n1)"
			xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $rVGA --above $HDMI > /dev/null 2>&1
			else
			echo "El monitor tiene una resolucion correcta? si/no"
			read mn
				if [ "$mn" == "n" ] || [ "$mn" == "no" ] || [ "$mn" == "No" ] || [ "$mn" == "NO" ] || [ "$lk" == "not" ] || [ "$lk" == "NOT" ] || [ "$Not" == "N" ]
				then
					xrandr | grep '*' | tail -n 1 | sort -r | awk '{print substr($0,4, length($0) -13)}'
					echo "Ingrese la resolucion"
					read res
					pcmanfm-qt -w "$(find $ubicacion/above.png -type f | shuf -n1)"
					xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $res --above $HDMI > /dev/null 2>&1
					echo "Echo resoluccion seleccionada"
					 
				else
				echo "Aplicado..."
				 
				fi
   	   		fi
   	   		else
   	   		echo "abajo?"
   	   		read down
   	   		if [ "$down" == "y" ] || [ "$down" == "yes" ] || [ "$down" == "YES" ] || [ "$down" == "Y" ] || [ "$down" == "si" ] || [ "$down" == "sí" ] || [ "$down" == "SI" ] || [ "$down" == "SÍ" ] || [ "$down" == "s" ] || [ "$down" == "S" ]
   	   		then
   	   		pcmanfm-qt -w "$(find $ubicacion/down.png -type f | shuf -n1)"
   	   		xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $rVGA --below $HDMI > /dev/null 2>&1
   	   			if [ $? -ne 0 ]
   	   			then
   	   			echo "No hay dispositivos HDMI conectados..."
				pcmanfm-qt -w "$(find $ubicacion/down.png -type f | shuf -n1)"
				xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $rVGA --below $HDMI > /dev/null 2>&1
				else
				echo "El monitor tiene una resolucion correcta? si/no"
				read mn
					if [ "$mn" == "n" ] || [ "$mn" == "no" ] || [ "$mn" == "No" ] || [ "$mn" == "NO" ] || [ "$lk" == "not" ] || [ "$lk" == "NOT" ] || [ "$Not" == "N" ]
					then
						xrandr | grep '*' | tail -n 1 | sort -r | awk '{print substr($0,4, length($0) -13)}'
						echo "Ingrese la resolucion"
						read res
						pcmanfm-qt -w "$(find $ubicacion/down.png -type f | shuf -n1)"
						xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $res --below $HDMI > /dev/null 2>&1
						echo "Echo resoluccion seleccionada"
					else
					echo "Aplicado..."
					fi
   	   			fi
   	   		else
   	   		echo "Izquierda?"
   	   		read left
   	   		if [ "$left" == "y" ] || [ "$left" == "yes" ] || [ "$left" == "YES" ] || [ "$left" == "Y" ] || [ "$left" == "si" ] || [ "$left" == "sí" ] || [ "$left" == "SI" ] || [ "$left" == "SÍ" ] || [ "$left" == "s" ] || [ "$left" == "S" ]
   	   		then
   	   		pcmanfm-qt -w "$(find $ubicacion/left.png -type f | shuf -n1)"
   	   		xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $rVGA --left-of $HDMI > /dev/null 2>&1
   	   			if [ $? -ne 0 ]
   	   			then
   	   			echo "No hay dispositivos HDMI conectados..."
				pcmanfm-qt -w "$(find $ubicacion/left.png -type f | shuf -n1)"
				xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $rVGA --left-of $HDMI > /dev/null 2>&1
				else
				echo "El monitor tiene una resolucion correcta? si/no"
				read mn
					if [ "$mn" == "n" ] || [ "$mn" == "no" ] || [ "$mn" == "No" ] || [ "$mn" == "NO" ] || [ "$lk" == "not" ] || [ "$lk" == "NOT" ] || [ "$Not" == "N" ]
					then
						xrandr | grep '*' | tail -n 1 | sort -r | awk '{print substr($0,4, length($0) -13)}'
						echo "Ingrese la resolucion"
						read res
						pcmanfm-qt -w "$(find $ubicacion/left.png -type f | shuf -n1)"
						xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $res --left-of $HDMI > /dev/null 2>&1
						echo "Echo resoluccion seleccionada"
					else
					echo "Aplicado..."
					fi
   	   			fi
   	   		else
   	   		echo "Por defecto: ${HDMI} derecha"
   	   		pcmanfm-qt -w "$(find $ubicacion/right.jpg -type f | shuf -n1)"
   	   		xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $rVGA --left-of $HDMI > /dev/null 2>&1
   	   		if [ $? -ne 0 ]
   	   			then
   	   			echo "No hay dispositivos HDMI conectados..."
				pcmanfm-qt -w "$(find $ubicacion/left.png -type f | shuf -n1)"
				xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $rVGA --left-of $HDMI > /dev/null 2>&1
				else
				echo "El monitor tiene una resolucion correcta? si/no"
				read mn
					if [ "$mn" == "n" ] || [ "$mn" == "no" ] || [ "$mn" == "No" ] || [ "$mn" == "NO" ] || [ "$lk" == "not" ] || [ "$lk" == "NOT" ] || [ "$Not" == "N" ]
					then
						xrandr | grep '*' | tail -n 1 | sort -r | awk '{print substr($0,4, length($0) -13)}'
						echo "Ingrese la resolucion"
						read res
						pcmanfm-qt -w "$(find $ubicacion/left.png -type f | shuf -n1)"
						xrandr --output $HDMI --mode $rHDMI --pos 0x0 --output $VGA --mode $res --left-of $HDMI > /dev/null 2>&1
						echo "Echo resoluccion seleccionada"
					else
					echo "Aplicado..."
					fi
   	   			fi	
   	   		fi	
   	   		fi
   	   		fi
   	   	
		fi
	fi
else
echo "Ok, Apagando HDMI"
xrandr --output $HDMI --off
pcmanfm-qt -w "$(find $ubicacion/wallpaper2.jpg -type f | shuf -n1)"  
fi


#Tiempo invertido 72h:02
#xrandr | grep -Pw "HDMI" 
#xdpyinfo | grep 'dimensions:'
#xrandr | grep '*' | tail -n 1 | sort -r | awk '{print substr($0,4, length($0) -13)}'
#xrandr | grep '*' | sort -r | tail -n 1 | awk '{print substr($0,4, length($0) -13)}'
#arriba de vga1 xrandr --output VGA-1 --mode 1440x900 --pos 0x0 --output HDMI-1 --mode 1680x1050 --above VGA-1 > /dev/null 2>&1
#abajo de vga1 xrandr --output VGA-1 --mode 1440x900 --pos 0x0 --output HDMI-1 --mode 1680x1050 --below VGA-1 > /dev/null 2>&1
#izquierda de vga1 xrandr --output VGA-1 --mode 1440x900 --pos 0x0 --output HDMI-1 --mode 1680x1050 --left-of VGA-1 > /dev/null 2>&1
#derecha de vga1 xrandr --output VGA-1 --mode 1440x900 --pos 0x0 --output HDMI-1 --mode 1680x1050 --right-of VGA-1 > /dev/null 2>&1
#
#
#
#
#
#
#
#
#
#
#
#
#
#
